apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-30T08:47:32Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "3050"
  uid: 6ba2c60d-d1e1-43a8-965b-992cb98d1e1d
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.103.102.69
  clusterIPs:
  - 10.103.102.69
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31617
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
